# specify which database and adapter to use for which environment

development:
  adapter: postgresql
  database: rush-hour-2-development

test:
  adapter: postgresql
  database: rush-hour-2-test

production:
  adapter: postgresql
  database: rush-hour-2-production
